name: Build and Push Docker Image

on:
  # Manual trigger the workflow
  workflow_dispatch:
    image_registry:
      required: false
      default: 'quay.io'
    release_tag:
      required: false
      default: 'next'

  # Every first day of the month
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              echo "IMAGE_REGISTRY=${{ github.event.inputs.image_registry }}" >> $GITHUB_ENV
              echo "RELEASE_TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
              echo "IMAGE_REGISTRY=quay.io" >> $GITHUB_ENV
              echo "RELEASE_TAG=next" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "release" ]]; then
              :
          fi

      - name: Build container image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: retis
          tags: ${{ env.RELEASE_TAG }}

#      - name: Push container image
#        id: push_image
#        uses: redhat-actions/push-to-registry@v2
#        with:
#          image: ${{ steps.build_image.outputs.image }}
#          tags: ${{ steps.build_image.outputs.tags }}
#          registry: env.IMAGE_REGISTRY

      - name: Show outputs
        run: |
          echo "${{ toJSON(steps.push_image.outputs) }}"
